//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompxERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermenust
    {
        public int mencode { get; set; }
        public int menuser { get; set; }
        public Nullable<bool> menview { get; set; }
        public Nullable<bool> menaddi { get; set; }
        public Nullable<bool> menedit { get; set; }
        public Nullable<bool> mendele { get; set; }
        public Nullable<bool> menacce { get; set; }
    }
}
